### ISSUE TITLE
Cannot Run Docker Compose Up

### ISSUE THREAD

**Issue by hezbymuhammad** [mtsmfm/yaichi#10]
# Background

Thank you for creating this amazing reverse proxy. I'm new to this and want to contribute especially on features to enrich information displayed on yaichi 😄 

# Problem

Running `docker-compose up` on newly forked yaichi resulted on error:

```bash
Command failed with status (1): [gcc -g -std=gnu99 -O3 -Wall -Werror-implic...]
/usr/local/src/ngx_mruby/mruby/tasks/mruby_build_commands.rake:31:in `_run'
/usr/local/src/ngx_mruby/mruby/tasks/mruby_build_commands.rake:36:in `rescue in _run'
/usr/local/src/ngx_mruby/mruby/tasks/mruby_build_commands.rake:32:in `_run'
/usr/local/src/ngx_mruby/mruby/tasks/mruby_build_commands.rake:89:in `run'
/usr/local/src/ngx_mruby/mruby/tasks/mruby_build_commands.rake:113:in `block (2 levels) in define_rules'
Command failed with status (1): ["gcc" -g -std=gnu99 -O3 -Wall -Werror-impl...]
/usr/local/src/ngx_mruby/mruby/tasks/mruby_build_commands.rake:33:in `_run'
/usr/local/src/ngx_mruby/mruby/tasks/mruby_build_commands.rake:89:in `run'
/usr/local/src/ngx_mruby/mruby/tasks/mruby_build_commands.rake:113:in `block (2 levels) in define_rules'
Tasks: TOP => default => all => /usr/local/src/ngx_mruby/mruby/build/host/lib/libmruby.flags.mak => /usr/local/src/ngx_mruby/mruby/build/host/lib/libmruby.a => /usr/local/src/ngx_mruby/mruby/build/host/mrbgems/mruby-redis/src/mrb_redis.o
(See full trace by running task with --trace)
make: *** [Makefile:70: build_mruby] Error 1
```

# Reference

Forked: https://github.com/hezbymuhammad/yaichi
Full log: [log.txt](https://github.com/mtsmfm/yaichi/files/2732548/log.txt)

**Comment by mtsmfm** [comment]
@hezbymuhammad 

Sorry for the late reply 🙇 
I've found build_config.rb doesn't specify mgem versions so always the latest versions are used.

https://github.com/mtsmfm/yaichi/blob/7942538dfd207c9bcd7751c9a279bbf78be73673/build_config.rb#L17-L33

I need to find the version I used at the time...

**Comment by hezbymuhammad** [comment]
Ah I see 👍 
Is there anything I can do to help?

**Comment by mtsmfm** [comment]
We need to find and specify the revision which can build or update ngx_mruby.
I guess latter is easier.

I'll do that but recently I spend my time in another project so it takes a while.
I'm very happy and will merge quickly if you fix the build 🙇
